[server]
debug_trace = false

[bluemix]
iam_url = "https://iam.bluemix.net"
iam_client_id = "bx"
iam_client_secret = "bx"
iam_api_key = "53GL6CsuRLWnK95MOCxcYiItl5v0NctLpa7CL_D6ideP"
refresh_token = ""


[softlayer]
softlayer_block_enabled = false
softlayer_block_provider_name = "SOFTLAYER-BLOCK"
softlayer_file_enabled = false
softlayer_file_provider_name = "SOFTLAYER-FILE"
softlayer_username = ""
softlayer_api_key = ""
softlayer_endpoint_url = "https://api.softlayer.com/rest/v3"
softlayer_iam_endpoint_url = "https://api.softlayer.com/mobile/v3"
softlayer_datacenter = "mex01"
softlayer_api_timeout = "30s"
softlayer_vol_provision_timeout = "30m"
softlayer_api_retry_interval = "5s"

[genesis]
genesis_provider_enabled = false
genesis_user_name = ""
genesis_api_key = ""
genesis_url = ""

[vpc]
vpc_enabled = true
vpc_block_provider_name = "vpc-classic"
vpc_username = ""# keep blank for IAM auth
vpc_api_key = "" # keep blank for IAM auth
vpc_endpoint_url = "https://us-south.iaas.cloud.ibm.com:443/v1"
vpc_timeout = "120s"
max_retry_attempt  = 5
max_retry_gap =  30
api_version = "2019-01-01"
